# put your own k3os configuration overrides here
# more info: https://github.com/rancher/k3os#configuration-reference

write_files:
- encoding: ""
  content: |-
    /dev/cdrom          /media/cdrom      iso9660         noauto,ro       0 0
    /dev/usbdisk        /media/usb        vfat            noauto,ro       0 0
    /dev/mmcblk0p1      /media/mmcblk0p1  vfat            rw              0 0

  owner: root:root
  path: /etc/fstab
  permissions: '0644'
boot_cmd:
- "mount -a"
k3os:
    password: test
