name: Build Images

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-rpi3:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the RPI image file
      run: sudo ./scripts/build.sh rpi3
    - name: Upload image file artifact
      uses: actions/upload-artifact@v1
      with:
        name: k3os-rpi3.img.gz
        path: build/image/rpi.img.gz
